// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.22.0
// source: shared/errstat/errors.proto

package errstat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorDetailCode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ErrorDetailCode) Reset() {
	*x = ErrorDetailCode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_errstat_errors_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorDetailCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetailCode) ProtoMessage() {}

func (x *ErrorDetailCode) ProtoReflect() protoreflect.Message {
	mi := &file_shared_errstat_errors_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetailCode.ProtoReflect.Descriptor instead.
func (*ErrorDetailCode) Descriptor() ([]byte, []int) {
	return file_shared_errstat_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetailCode) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ErrorDetailCause struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cause *anypb.Any `protobuf:"bytes,1,opt,name=cause,proto3" json:"cause,omitempty"`
}

func (x *ErrorDetailCause) Reset() {
	*x = ErrorDetailCause{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_errstat_errors_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorDetailCause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetailCause) ProtoMessage() {}

func (x *ErrorDetailCause) ProtoReflect() protoreflect.Message {
	mi := &file_shared_errstat_errors_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetailCause.ProtoReflect.Descriptor instead.
func (*ErrorDetailCause) Descriptor() ([]byte, []int) {
	return file_shared_errstat_errors_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorDetailCause) GetCause() *anypb.Any {
	if x != nil {
		return x.Cause
	}
	return nil
}

type ErrorDetailReason struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *ErrorDetailReason) Reset() {
	*x = ErrorDetailReason{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_errstat_errors_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorDetailReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetailReason) ProtoMessage() {}

func (x *ErrorDetailReason) ProtoReflect() protoreflect.Message {
	mi := &file_shared_errstat_errors_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetailReason.ProtoReflect.Descriptor instead.
func (*ErrorDetailReason) Descriptor() ([]byte, []int) {
	return file_shared_errstat_errors_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorDetailReason) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ErrorDetailDevMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DevMessage string `protobuf:"bytes,1,opt,name=dev_message,json=devMessage,proto3" json:"dev_message,omitempty"`
}

func (x *ErrorDetailDevMessage) Reset() {
	*x = ErrorDetailDevMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_errstat_errors_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorDetailDevMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetailDevMessage) ProtoMessage() {}

func (x *ErrorDetailDevMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_errstat_errors_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetailDevMessage.ProtoReflect.Descriptor instead.
func (*ErrorDetailDevMessage) Descriptor() ([]byte, []int) {
	return file_shared_errstat_errors_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorDetailDevMessage) GetDevMessage() string {
	if x != nil {
		return x.DevMessage
	}
	return ""
}

type ErrorDetailTraceId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
}

func (x *ErrorDetailTraceId) Reset() {
	*x = ErrorDetailTraceId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shared_errstat_errors_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorDetailTraceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetailTraceId) ProtoMessage() {}

func (x *ErrorDetailTraceId) ProtoReflect() protoreflect.Message {
	mi := &file_shared_errstat_errors_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetailTraceId.ProtoReflect.Descriptor instead.
func (*ErrorDetailTraceId) Descriptor() ([]byte, []int) {
	return file_shared_errstat_errors_proto_rawDescGZIP(), []int{4}
}

func (x *ErrorDetailTraceId) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

var File_shared_errstat_errors_proto protoreflect.FileDescriptor

var file_shared_errstat_errors_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x65, 0x72, 0x72, 0x73, 0x74, 0x61, 0x74,
	0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x64,
	0x34, 0x6c, 0x2e, 0x6d, 0x65, 0x78, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x1a, 0x19, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61,
	0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0f, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22,
	0x3e, 0x0a, 0x10, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x43, 0x61,
	0x75, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x22,
	0x2b, 0x0a, 0x11, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x38, 0x0a, 0x15,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x44, 0x65, 0x76, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2f, 0x0a, 0x12, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x54, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x42, 0x49, 0x5a, 0x47, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x73, 0x75, 0x6e, 0x64, 0x68, 0x65, 0x69, 0x74,
	0x73, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f, 0x72, 0x6b, 0x69, 0x2d, 0x6d, 0x65, 0x78, 0x2d, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x6d, 0x65, 0x78, 0x2f, 0x73, 0x68, 0x61, 0x72,
	0x65, 0x64, 0x2f, 0x65, 0x72, 0x72, 0x73, 0x74, 0x61, 0x74, 0x3b, 0x65, 0x72, 0x72, 0x73, 0x74,
	0x61, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shared_errstat_errors_proto_rawDescOnce sync.Once
	file_shared_errstat_errors_proto_rawDescData = file_shared_errstat_errors_proto_rawDesc
)

func file_shared_errstat_errors_proto_rawDescGZIP() []byte {
	file_shared_errstat_errors_proto_rawDescOnce.Do(func() {
		file_shared_errstat_errors_proto_rawDescData = protoimpl.X.CompressGZIP(file_shared_errstat_errors_proto_rawDescData)
	})
	return file_shared_errstat_errors_proto_rawDescData
}

var file_shared_errstat_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_shared_errstat_errors_proto_goTypes = []interface{}{
	(*ErrorDetailCode)(nil),       // 0: d4l.mex.errors.ErrorDetailCode
	(*ErrorDetailCause)(nil),      // 1: d4l.mex.errors.ErrorDetailCause
	(*ErrorDetailReason)(nil),     // 2: d4l.mex.errors.ErrorDetailReason
	(*ErrorDetailDevMessage)(nil), // 3: d4l.mex.errors.ErrorDetailDevMessage
	(*ErrorDetailTraceId)(nil),    // 4: d4l.mex.errors.ErrorDetailTraceId
	(*anypb.Any)(nil),             // 5: google.protobuf.Any
}
var file_shared_errstat_errors_proto_depIdxs = []int32{
	5, // 0: d4l.mex.errors.ErrorDetailCause.cause:type_name -> google.protobuf.Any
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shared_errstat_errors_proto_init() }
func file_shared_errstat_errors_proto_init() {
	if File_shared_errstat_errors_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shared_errstat_errors_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorDetailCode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_errstat_errors_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorDetailCause); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_errstat_errors_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorDetailReason); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_errstat_errors_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorDetailDevMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shared_errstat_errors_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorDetailTraceId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shared_errstat_errors_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_errstat_errors_proto_goTypes,
		DependencyIndexes: file_shared_errstat_errors_proto_depIdxs,
		MessageInfos:      file_shared_errstat_errors_proto_msgTypes,
	}.Build()
	File_shared_errstat_errors_proto = out.File
	file_shared_errstat_errors_proto_rawDesc = nil
	file_shared_errstat_errors_proto_goTypes = nil
	file_shared_errstat_errors_proto_depIdxs = nil
}
