// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package datamodel

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BlobStore struct {
	BlobName string
	BlobType string
	BlobOid  pgtype.Uint32
}

type CurrentItemValue struct {
	ID         string
	ItemID     string
	FieldName  string
	FieldValue string
	Place      int32
	Revision   int32
	Language   pgtype.Text
}

type Item struct {
	CreatedAt           pgtype.Timestamptz
	ID                  string
	Owner               string
	EntityName          string
	BusinessID          pgtype.Text
	BusinessIDFieldName pgtype.Text
	Hash                pgtype.Text
}

type ItemValue struct {
	CreatedAt       pgtype.Timestamptz
	ID              string
	Revision        int32
	Deleted         bool
	Language        pgtype.Text
	FieldName       string
	FieldValue      string
	Place           int32
	ItemID          string
	RevisionComment pgtype.Text
}

type ItemViewCount struct {
	CreatedAt pgtype.Timestamptz
	ItemID    string
	UserID    string
	Counts    int32
}

type ItemsNullableBusinessID struct {
	ItemID              string
	CreatedAt           pgtype.Timestamptz
	Owner               string
	EntityName          string
	BusinessID          pgtype.Text
	BusinessIDFieldName pgtype.Text
}

type ItemsWithBusinessID struct {
	ItemID              string
	CreatedAt           pgtype.Timestamptz
	Owner               string
	EntityName          string
	BusinessID          string
	BusinessIDFieldName pgtype.Text
}

type LatestItemsWithBusinessID struct {
	ItemID              string
	CreatedAt           pgtype.Timestamptz
	Owner               string
	EntityName          string
	BusinessID          string
	BusinessIDFieldName pgtype.Text
}

type Relation struct {
	CreatedAt    pgtype.Timestamptz
	ID           string
	Deleted      bool
	Owner        string
	SourceItemID string
	Type         string
	TargetItemID string
	InfoItemID   pgtype.Text
}
